import Image from "next/image";
import { Check } from "lucide-react";
import { SiteHeader } from "@/components/site/SiteHeader";
import { SiteFooter } from "@/components/site/SiteFooter";
import { FlameDetectorGrid } from "@/components/products/FlameDetectorGrid";
import { FlameDetectorFaq } from "@/components/products/FlameDetectorFaq";

const APPLICATIONS = [
  "Industrial Facilities",
  "Aerospace Safety",
  "Commercial Buildings",
  "Oil & Gas Sector",
  "Marine Safety",
];

const DETECTOR_TYPES = [
  {
    title: "Ultraviolet (UV) Flame Detectors",
    body: "Sensitive to the UV light emitted by flames, these detectors excel at high-speed detection of open flames. They are particularly well-suited for industrial settings, where rapid response is vital.",
  },
  {
    title: "Infrared (IR) Flame Detectors",
    body: "IR detectors respond to the infrared radiation produced by flames. They are perfect for environments where potential false alarms from sunlight or artificial lighting are a concern. Accuracy is their hallmark.",
  },
  {
    title: "Visible Light Flame Detectors",
    body: "Versatile and adaptable, these detectors react to visible light generated by flames. Their broad range of applications makes them a go-to choice for many different industries.",
  },
  {
    title: "Combination Flame Detectors",
    body: "For those who demand the highest level of flame detection accuracy, combination flame detectors are the answer. They incorporate UV, IR, and visible light sensors, reducing false alarms and enhancing overall performance.",
  },
];

export default function FlameDetectorPage() {
  return (
    <>
      <SiteHeader />
      <main>
        {/* ── Hero ──────────────────────────────────────────────────── */}
        <section
          aria-labelledby="fld-hero-heading"
          style={{ background: "var(--surface-primary)",  }}
        >
          <div className="max-w-[var(--container-max)] mx-auto px-5 md:px-8">
            <div className="grid grid-cols-1 lg:grid-cols-[1fr_480px] xl:grid-cols-[1fr_560px] items-center">

              {/* Left: copy */}
              <div className="py-12 md:py-16 lg:py-20 flex flex-col">
                <span className="t-label block mb-4" style={{ color: "var(--content-brand)" }}>
                  Flame Detectors
                </span>
                <h1
                  id="fld-hero-heading"
                  className="t-h1"
                  style={{
                    margin: "0 0 20px",
                    textWrap: "balance",
                    fontSize: "clamp(26px, 4vw, 36px)",
                    lineHeight: "clamp(34px, 5vw, 44px)",
                  }}
                >
                  Yamin Global Flame Detector: Advanced Fire Safety Solutions
                </h1>
                
                <p className="t-body-lg t-secondary" style={{ margin: 0, maxWidth: 520 }}>
                  A flame detector is not just a safety device; it&apos;s a sentinel that watches over your
                  surroundings, ready to take action when it matters most. These advanced devices can detect
                  the presence of an open flame or fire by sensing specific wavelengths of light emitted by
                  flames, including ultraviolet (UV), infrared (IR), and visible light.
                </p>
              </div>

              {/* Right: image */}
              <div className="w-full flex items-center justify-center lg:justify-end">
                <Image
                  src="/Pumpjack-B2.png"
                  alt="Industrial environment for flame detection"
                  width={560}
                  height={480}
                  priority
                  sizes="(max-width: 1024px) 100vw, 560px"
                  className="w-full h-auto lg:max-h-[480px] object-contain"
                />
              </div>

            </div>
          </div>
        </section>

        {/* ── Product grid ──────────────────────────────────────────── */}
        <FlameDetectorGrid />

        {/* ── Technology + Applications ──────────────────────────── */}
        <section
          aria-labelledby="fld-tech-heading"
          style={{ background: "var(--surface-secondary)", borderTop: "1px solid var(--border-primary)", borderBottom: "1px solid var(--border-primary)" }}
        >
          <div className="max-w-[var(--container-max)] mx-auto px-5 md:px-8 py-12 md:py-20">
            <div className="grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-12 lg:gap-20">

              {/* Left: technology */}
              <div>
                <h2 id="fld-tech-heading" className="t-h2" style={{ margin: "0 0 16px" }}>
                  Discover the Cutting-Edge Technology Behind Flame Detectors
                </h2>
                <p className="t-body-lg t-secondary" style={{ margin: 0, maxWidth: 580 }}>
                  Welcome to the world of flame detectors, where safety meets innovation. We&apos;ll delve into
                  the incredible technology that powers flame detectors, explore their extensive applications,
                  and introduce you to a range of exceptional products designed to safeguard your environment.
                </p>
              </div>

              {/* Right: applications */}
              <div>
                <h3 style={{ margin: "0 0 20px", fontSize: 20, fontWeight: 600 }}>Applications</h3>
                <ul className="flex flex-col gap-3 list-none m-0 p-0">
                  {APPLICATIONS.map((app) => (
                    <li key={app} className="flex items-center gap-3">
                      <span
                        className="inline-flex items-center justify-center shrink-0"
                        style={{
                          width: 22,
                          height: 22,
                          borderRadius: "999px",
                          background: "var(--surface-brand-subtle)",
                        }}
                      >
                        <Check size={13} color="var(--content-brand)" strokeWidth={2.5} />
                      </span>
                      <span style={{ fontSize: 15, color: "var(--content-secondary)" }}>{app}</span>
                    </li>
                  ))}
                </ul>
              </div>

            </div>
          </div>
        </section>

        {/* ── Detector types grid ───────────────────────────────────── */}
        <section
          aria-labelledby="fld-types-heading"
          style={{ background: "var(--surface-primary)", borderBottom: "1px solid var(--border-primary)" }}
        >
          <div className="max-w-[var(--container-max)] mx-auto px-5 md:px-8 py-12 md:py-20">
            <h2 id="fld-types-heading" className="t-h2" style={{ margin: "0 0 40px" }}>
              Types of Flame Detectors
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-px" style={{ border: "1px solid var(--border-primary)", borderRadius: "var(--radius-lg)", overflow: "hidden", background: "var(--border-primary)" }}>
              {DETECTOR_TYPES.map((type) => (
                <div
                  key={type.title}
                  className="p-8"
                  style={{ background: "var(--surface-primary)" }}
                >
                  <h3 style={{ margin: "0 0 16px", fontSize: 20, fontWeight: 600, lineHeight: "28px" }}>
                    {type.title}
                  </h3>
                  <p style={{ margin: 0, fontSize: 14, lineHeight: "22px", color: "var(--content-secondary)" }}>
                    {type.body}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── FAQ ───────────────────────────────────────────────────── */}
        <FlameDetectorFaq />
      </main>
      <SiteFooter />
    </>
  );
}
